seed: 1
network: 'dsv3'
fr_num: 10
v_hdim: 128
mlp_dim: [128, 64]
cnn_fdim: 256
lr: 1.e-4
num_epoch: 50
shuffle: true
save_model_interval: 100
num_sample: 50000
sub_sample: 5
fr_margin: 3
batch_size: 2
bi_dir: true
loss: 'focal'